### ISSUE TITLE
哔哩轻小说解析章节失败

### ISSUE THREAD

**Issue by yuduotianguang** [feiyeyuanye/LittleHelperIssues#2]

**Comment by feiyeyuanye** [comment]
GitHub 上已更新，顺便提示一下：
- 每个章节，会一次性加载所有页的内容(比如有十页，会请求十次)。所以，页数多的情况下，加载会慢。
- 加载内容时，同时请求网络图片，第一次获取图片时，不知道图片高度，所以第一次进入章节时默认每张图片占一页。
